from typing import Protocol, Any, Dict
from src.validator.registry import StateRegistry

class Workload(Protocol):
    def build_model(self) -> Any: ...
    def build_optimizer(self, model: Any) -> Any: ...
    def build_scheduler(self, optimizer: Any) -> Any: ...
    def build_data(self) -> Any: ...
    
    def train_step(self, *args, **kwargs) -> Any: ...
    def evaluate(self, *args, **kwargs) -> Any: ...
    
    def register_state_contracts(self, registry: StateRegistry, context: Any) -> None: ...
